### ISSUE TITLE
add pickup day option

### ISSUE THREAD

**Issue by binkboyd** [jkaberg/trv-ical-server#2]
I guess most areas have a regular day when the trash is picked up - it would be nice with an additional parameter to specify the pickup day. This would then produce an event on that day, and not an event which covers the whole week (and clutters my dakboard :) )

**Comment by jkaberg** [comment]
@binkboyd you mean like an additional url parameter to "hardcode" the pickup day? Something like `https://trv-ical.eth0.sh/741?day=friday`?

Idealy one would get this from [the API](https://trv.no/wp-json/wasteplan/v1/calendar/741), but `"day_of_week":null` 😞

**Comment by jkaberg** [comment]
@binkboyd So I pushed an commit, check it out https://github.com/jkaberg/trv-ical-server/commit/7d27514623df9fd2549b708a3740c63eef290580

**Comment by binkboyd** [comment]
Nice - :100: :)
